site_name: NCSSM 2025 TSA Drone Documentation

nav:
  - Ideation: ideation.md
  - Electrical Engineering: ee.md
  - Programming: programming.md
  - CAD: cad.md
  - Assembly: assembly.md
  - Testing: testing.md


theme: material
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
